#!/usr/bin/env node
/*!
 * Copyright (c) 2020 Digital Bazaar, Inc. All rights reserved.
 */
'use strict';

const cgbot = require('.');
const fsp = require('fs').promises;
const lockfile = require('lockfile');
const process = require('process');

// ignore self-signed TLS cert
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

// run the program
main();

async function main() {
  require('yargs')
    .usage('Usage: $0 <command>')
    .option('verbose', {
      describe: 'Provide verbose logging',
      alias: 'v',
      boolean: true
    })
    .option('config', {
      describe: 'Connection configuration file',
      alias: 'c'
    })
    .alias('h', 'help')
    .help('help', 'Show help for cborld command.')
    .demandOption('config')
    .command('monitor', 'Monitors the meeting server XMPP channels.',
      yargs => {
        yargs
          .example([
            ['$0 -c /etc/cgbot/ccg.cfg monitor',
              'Monitors using the configuration information provided.']
          ]);
      }, monitorCommand)
    .command('manage', 'Manage a specific XMPP and IRC channel.',
      yargs => {
        yargs
          .option('meeting', {
            describe: 'The meeting to manage.',
            alias: 'm'
          })
          .demandOption('meeting')
          .example([
            ['$0 -c /etc/cgbot/ccg.cfg manage --meeting weekly',
              'Manages a meeting using the provided config.']
          ]);
      }, manageCommand)
    .demandCommand(1, 'You need to specify a command.')
    .argv;
}

// Yargs command to monitor
async function monitorCommand(args) {
  // attempt to monitor channels
  try {
    const config = JSON.parse(await fsp.readFile(args.config));
    const meetings = Object.keys(config.meetings).join(', ');
    const domain = config.xmppOptions.domain;
    checkLockfile('/var/tmp/cgbot-monitor.lock');
    console.log(`Monitoring ${domain} for meetings: ${meetings}.`);
    await cgbot.monitor(config);
  } catch(e) {
    console.error(e.stack);
    process.exit(1);
  }
}

// Yargs command to manage
async function manageCommand(args) {
  try {
    const config = JSON.parse(await fsp.readFile(args.config));
    const domain = config.xmppOptions.domain;
    const meeting = args.meeting;
    if(!config.meetings[meeting]) {
      console.error(`Unknown meeting '${meeting}' in ${args.config}.`);
      process.exit(1);
    }

    console.log(`Managing https://${domain}/${meeting}.`);
    checkLockfile(`/var/tmp/cgbot-manage-${meeting}.lock`);
    await cgbot.manage({meeting: args.meeting, ...config});
  } catch(e) {
    console.error(e.stack);
    process.exit(1);
  }
}

function checkLockfile(lockFilename) {
  // create a lockfile that goes stale after 130 minutes
  try {
    lockfile.lockSync(lockFilename, {stale: 7800000});
  } catch(e) {
    console.log(e, '\nError: Another cgbot instance exists.');
    process.exit(1);
  }

  // cleanup the lockfile if there is an uncaught exception or an interrupt
  process.on('uncaughtException', err => {
    console.log('uncaught exception: ', err.stack);
    lockfile.unlockSync(lockFilename);
    process.exit(1);
  });

  process.on('SIGINT', () => {
    console.log('\nCleaning up lock file and exiting.');
    lockfile.unlockSync(lockFilename);
    process.exit(1);
  });
}
